name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.Docker_passwd }}" | docker login -u "visnudev" --password-stdin
        docker build -t visnu-flask-app-githubactions:latest ./Task4-github_action/.
        docker push visnu-flask-app-githubactions:latest
